# Generated by Django 3.1.5 on 2021-02-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_water'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='water',
            options={'ordering': ['-visit']},
        ),
        migrations.AlterField(
            model_name='water',
            name='visit',
            field=models.DateField(verbose_name='visit date'),
        ),
    ]
